### PR TITLE
Plugin system with authentication and userlist plugin.

### PR DESCRIPTION
**Pull request by timschwartz**

### CODE REVIEW

**Comment by sirkitree** [comment]
Wow, this is really impressive @timschwartz! I haven't tested it out yet, but gave the code a peruse this morning. I won't be around much today to test most likely but I'll try as soon as possible.

* I really like the Plugin architecture you've come up with. I'm wondering how you see people installing plugins. It would be good to have some instructions around that in the near future. For instance if someone writes a totally separate plugin that you can install with npm, how would that work?
* I'd like to tag the current version and start [semantic versioning](http://semver.org/). Then this is a large enough architecture change that we would tag a new major version since it's not entirely backwards compatible. It mostly is, but we have no automatic cleanup if someone has existing tables and such, so I'd term this a breaking change. But perhaps we merge this and tag as the first major version and write up some instructions on how to upgrade from a previous version. Thoughts?
* There is some indenting that could be fixed. Each line within a function() should be indented.
* Lastly, I'd love to get @source83's review of this since it touches much of what he wrote, moving it out of the core and into a plugin. @source83 if you don't have time, that's fine, just let us know.

**Comment by timschwartz** [comment]
>For instance if someone writes a totally separate plugin that you can install with npm, how would that work?

We could include the node_modules/ directory in the plugin search path.

**Comment by timschwartz** [comment]
I'm going to make a few changes and repush this.

**Comment by sirkitree** [comment]
Was just about to reply when you closed this... you can actually just push to the branch to make changes.

**Comment by timschwartz** [comment]
OK, I've created packages janus-mysql-auth and janus-mysql-userlist on npm and adjusted janus-server to use them.

**Comment by sirkitree** [comment]
Dude, you're amazing! :) I should be able to give this a try within the hour :+1:

**Comment by sirkitree** [comment]
Tested locally and I'm still able to connect. npm install the plugins and they run just fine as far as I can tell. the users table was created locally, already had access_statistics.

The php script that is currently in the lobby displaying the user online is reading from the `online_users` table which was installed as a result of the previous code. This table only ever held user names as they signed in and removed them on log out. What would be the new method of detecting online users since this seems to hold users in the new `users` table indefinitely?

**Comment by timschwartz** [comment]
You should widen the ip column of access_statistics to 40 characters so it will fit IPv6 addresses.

Use this query to see currently online users:

"SELECT `userId`, `roomId`, `ip`, `note`, `client_version` FROM `users` WHERE `updated_at` > DATE_SUB(NOW() , INTERVAL 10 SECOND)"

**Comment by sirkitree** [comment]
Ah, so that table is updated on an interval. Ok I didn't realize that. Thank you.

Another question: If I wanted to authenticate against the VR Sites user base, I'd need to create my own authentication module, similar to janus-mysql-auth, and use that one instead, correct?

**Comment by timschwartz** [comment]
Right, you would just need to modify the queries a bit.

**Comment by sirkitree** [comment]
Ok, cool. I think this is okay to merge. Really great work @timschwartz! Thank you so much :grinning: 

It'll take me a bit to deploy on VR Sites and get that php script changed up. I think once this and the config changes are merged, I'm going to cut our first release: v0.1.0

**Comment by timschwartz** [comment]
Cool.

**Pull request merged**
