### PR TITLE
Default website and JanusVR room for the Janus VR Presence Server

### PR DESCRIPTION
**Pull request by oculushut**
Quite a few file changes here, but the main things to look out for:

1.  The change in the server.js which now has a route which will serve files held within the /public folder.
2.  The content of the /public folder is a basic Bootstrap template with some minor changes in the index.html for project specific content (title, intro etc) and then additional folders to hold VR specific assets.
3.  Browsing to http://servername:8080 from a web browser will now bring up a webpage which is based on a Bootstrap template.  The website will look like this:

Landing Page
3.  Browsing to http://servername:8080 from JanusVR will look like this: https://youtu.be/Z4GwTUNZtcw

The idea is that we can show stats or other stuff on the web page and the VR room in the future.

Hopefully, if it all goes well then perhaps we can have a /private folder area which is only served to an administrator... and then they can control their instance of the multiplayer server like this! :p 

Janus VR Presence Server Version 50

### CODE REVIEW

**Comment by sirkitree** [comment]
I personally would like it better if the server should stick to socket transport and not present a website.

**Comment by oculushut** [comment]
Perhaps I make it configurable so it does not display by default?

**Comment by sirkitree** [comment]
Perhaps. I'd like to hear if others think this is valuable. I'm worried about express in general as it's been found to have memory leaks in some versions (not sure what version off the top of my head) but you can read this: http://techblog.netflix.com/2014/11/nodejs-in-flames.html

I don't want to discount your work here at all, as having a web view with things like status and such could be very useful, but typically the general approach for Node libraries is to make them do one thing really well and allow for interfaces or api's for extra functionality. So to me something like this might fit better in a subproject or a companion project. But then, it's not my project :wink: just expressing opinions. It could also be that we separate it out later and keep developing it here for now.

**Comment by oculushut** [comment]
Ok cool.  Will take a read of link tomorrow and can see what others want too.  Know what you mean about doing one thing well... Will be easier to scale later, if required too.  I can keep that bit of functionality separate on my own branch for now if it's not good for main branch.  Btw, what kinds of stats do you think will be useful?  And what do you think about oauth 2 for authentication on top of the local site authentication that source made?  Would that be a useful option?

**Comment by sirkitree** [comment]
Simple stats at first maybe, like is the server up or not. Could expand to things like users online, maybe some stats on urls visited.

OAuth could be huge IMHO. Especially if Janus used it for authentication, then websites could use it as well. Thinking about VR Sites using OAuth which would mean you could log into Janus and VR Sites with the same credentials. Then other people running servers could also use the same creds. Could be very useful.

**Comment by oculushut** [comment]
OK - that's good to know.  It's always fun to build JanusVR related stuff in general and a bonus if somebody finds it useful!  I may work on something stats related next, but won't necessarily be immediately useful for your production system... had a few ideas I would like to try out (they are probably more "cosmetic" and fun than "hardcode"!).

Btw, I had a look at the article from Netflix.  It sounds like they had a bug in the Netflix code and Node/Express was actually not to blame.  They had a routine which kept on adding a handler for the same route.  They said that it would have been nice if Express warned them about this by throwing an error, but it was a bug in the Netflix code in any case.  The flame graphs thing was an interesting visualisation.

Sounds like you've been burnt by memory leaks in the past - I think one of the worst bugs I have ever had to fix was a memory leak...  Also, funny to read that Netflix used the age old tried and tested magical - "have you tried switching it off and then back on again?" - trick on their servers.

**Comment by sirkitree** [comment]
Hrm, Guess I should have read that article a bit closer. Thanks!

**Comment by sirkitree** [comment]
i don't think we're going to implement this in it's current form. However, while we're coming up with the plugin architecture in #20 I'd like to keep this use case in mind so that something like this could be provided as a plugin for the sever.

Also of note is #22 where we're talking about removing the webserver altogether.

**Pull request closed without merging**
